export default {
  entryPagePath: 'pages/index/index',
  pages: [
    'pages/login/index',
    'pages/index/index',
     'pages/webview/index',
    'pages/activities/index',
    'pages/category/index',
    'pages/product-list/index',
    'pages/product-detail/index',
    'pages/store-detail/index',
    'pages/stores/index',
    'pages/order-detail/index',
    'pages/cart/index',
    'pages/checkout/index',
    'pages/orders/index',
    'pages/store-finance/index',
    'pages/store-accounts/index',
    'pages/coupons/index',
    'pages/address/index',
    'pages/membership/index',
    'pages/membership-orders/index',
    'pages/after-sale/index',
    'pages/feedback/index',
    'pages/help/index',
    'pages/terms/index',
    'pages/settings/index',
    'pages/about/index',
    'pages/privacy/index',
    'pages/profile/index',
    'pages/share/index',
    // add other pages here as needed
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'Tea App',
    navigationBarTextStyle: 'black',
  },
  tabBar: {
    color: '#666666',
    selectedColor: '#07c160',
    backgroundColor: '#ffffff',
    list: [
      { pagePath: 'pages/index/index', text: '首页' },
      { pagePath: 'pages/cart/index', text: '购物车' },
      { pagePath: 'pages/profile/index', text: '我的' },
    ],
  },
};
