#!/usr/bin/env bash
set -euo pipefail

# Assert membership flow results
# This script validates the JSON output files generated by run_membership_integration.sh
#
# Usage:
#   ./scripts/assert_membership_flow.sh [--strict]
#
# Options:
#   --strict: Enable strict mode with additional validations
#
# Requirements:
#   - jq installed
#   - membership_summary_after_purchase.json exists
#   - membership_b_flow_checked.json exists

STRICT_MODE=0
INPUT_DIR=${INPUT_DIR:-"build-ci-logs"}

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --strict)
      STRICT_MODE=1
      shift
      ;;
    *)
      echo "Unknown option: $1" >&2
      exit 1
      ;;
  esac
done

# Check for jq
if ! command -v jq >/dev/null 2>&1; then
  echo "ERROR: jq is required but not installed" >&2
  exit 1
fi

# Check for required files
SUMMARY_FILE="$INPUT_DIR/membership_summary_after_purchase.json"
FLOW_FILE="$INPUT_DIR/membership_b_flow_checked.json"

if [[ ! -f "$SUMMARY_FILE" ]]; then
  echo "ERROR: Required file not found: $SUMMARY_FILE" >&2
  echo "Please run scripts/run_membership_integration.sh first" >&2
  exit 1
fi

if [[ ! -f "$FLOW_FILE" ]]; then
  echo "ERROR: Required file not found: $FLOW_FILE" >&2
  echo "Please run scripts/run_membership_integration.sh first" >&2
  exit 1
fi

echo "========================================="
echo "Sprint B Membership Flow Assertions"
echo "Mode: $(if [[ $STRICT_MODE -eq 1 ]]; then echo "STRICT"; else echo "NORMAL"; fi)"
echo "========================================="

# Validate JSON files are well-formed
echo "[1] Validating JSON structure..."
if ! jq empty "$SUMMARY_FILE" 2>/dev/null; then
  echo "ERROR: $SUMMARY_FILE is not valid JSON" >&2
  exit 1
fi

if ! jq empty "$FLOW_FILE" 2>/dev/null; then
  echo "ERROR: $FLOW_FILE is not valid JSON" >&2
  exit 1
fi
echo "✓ JSON files are well-formed"

# Extract key values from flow check file
echo "[2] Checking flow validation results..."
package_list_ok=$(jq -r '.checks.package_list_retrieved' "$FLOW_FILE")
order_created=$(jq -r '.checks.order_created' "$FLOW_FILE")
payment_created=$(jq -r '.checks.payment_order_created' "$FLOW_FILE")
order_found=$(jq -r '.checks.order_found_in_list' "$FLOW_FILE")
all_passed=$(jq -r '.result.all_checks_passed' "$FLOW_FILE")
test_status=$(jq -r '.result.test_status' "$FLOW_FILE")

# Basic assertions (always checked)
FAILED=0

if [[ "$package_list_ok" != "true" ]]; then
  echo "✗ FAILED: Package list retrieval failed"
  FAILED=1
else
  echo "✓ Package list retrieved successfully"
fi

if [[ "$order_created" != "true" ]]; then
  echo "✗ FAILED: Order creation failed"
  FAILED=1
else
  echo "✓ Order created successfully"
fi

if [[ "$payment_created" != "true" ]]; then
  echo "✗ FAILED: Payment order creation failed"
  FAILED=1
else
  echo "✓ Payment order created successfully"
fi

if [[ "$order_found" != "true" ]]; then
  echo "✗ FAILED: Order not found in list"
  FAILED=1
else
  echo "✓ Order found in order list"
fi

# Strict mode additional checks
if [[ $STRICT_MODE -eq 1 ]]; then
  echo "[3] Running strict mode validations..."
  
  # Check order status
  order_status=$(jq -r '.data.order_status' "$FLOW_FILE")
  if [[ "$order_status" == "unknown" || "$order_status" == "null" ]]; then
    echo "✗ STRICT FAILED: Order status is unknown or null"
    FAILED=1
  else
    echo "✓ Order status is valid: $order_status"
  fi
  
  # Check payment status
  payment_status=$(jq -r '.data.payment_status' "$FLOW_FILE")
  if [[ "$payment_status" == "unknown" || "$payment_status" == "null" ]]; then
    echo "✗ STRICT FAILED: Payment status is unknown or null"
    FAILED=1
  else
    echo "✓ Payment status is valid: $payment_status"
  fi
  
  # Validate package_id and order_id are numeric
  package_id=$(jq -r '.data.package_id' "$FLOW_FILE")
  order_id=$(jq -r '.data.order_id' "$FLOW_FILE")
  
  if ! [[ "$package_id" =~ ^[0-9]+$ ]]; then
    echo "✗ STRICT FAILED: Package ID is not a valid number: $package_id"
    FAILED=1
  else
    echo "✓ Package ID is valid: $package_id"
  fi
  
  if ! [[ "$order_id" =~ ^[0-9]+$ ]]; then
    echo "✗ STRICT FAILED: Order ID is not a valid number: $order_id"
    FAILED=1
  else
    echo "✓ Order ID is valid: $order_id"
  fi
  
  # Check that summary file has all required fields
  echo "[4] Validating summary file completeness..."
  required_fields=("timestamp" "api_base" "package_id" "order_id" "test_status")
  for field in "${required_fields[@]}"; do
    value=$(jq -r ".$field // \"\"" "$SUMMARY_FILE")
    if [[ -z "$value" || "$value" == "null" ]]; then
      echo "✗ STRICT FAILED: Required field missing or null in summary: $field"
      FAILED=1
    else
      echo "✓ Summary field present: $field"
    fi
  done
fi

# Final result
echo ""
echo "========================================="
if [[ $FAILED -eq 0 ]]; then
  echo "✓ ALL ASSERTIONS PASSED"
  echo "Test Status: $test_status"
  echo "========================================="
  exit 0
else
  echo "✗ SOME ASSERTIONS FAILED"
  echo "Test Status: FAILED"
  echo "========================================="
  exit 1
fi
